"""
ASHRAE Energy Explorer — Streamlit Dashboard

Loads pre-computed data only (zero model inference at runtime).
All data from outputs/app_*.parquet files generated by
src/prepare_app_data.py.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_ROOT / "outputs"

METER_LABELS = {0: "Electricity", 1: "Chilled Water", 2: "Steam", 3: "Hot Water"}

PRIMARY_USE_LABELS = {
    0: "Education", 1: "Entertainment/public assembly",
    2: "Food sales and service", 3: "Healthcare",
    4: "Lodging/residential", 5: "Manufacturing/industrial",
    6: "Office", 7: "Other", 8: "Parking", 9: "Public services",
    10: "Religious worship", 11: "Retail", 12: "Services",
    13: "Technology/science", 14: "Utility", 15: "Warehouse/storage",
}


# ---------------------------------------------------------------------------
# Data loading (cached)
# ---------------------------------------------------------------------------
@st.cache_data
def load_building_summary() -> pd.DataFrame:
    return pd.read_parquet(OUTPUT_DIR / "app_building_summary.parquet")


@st.cache_data
def load_timeseries() -> pd.DataFrame:
    df = pd.read_parquet(OUTPUT_DIR / "app_timeseries.parquet")
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df


@st.cache_data
def load_shap_values() -> pd.DataFrame:
    return pd.read_parquet(OUTPUT_DIR / "app_shap_values.parquet")


# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="ASHRAE Energy Explorer",
    page_icon="🏢",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
summary_df = load_building_summary()
ts_df = load_timeseries()
shap_df = load_shap_values()

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
st.sidebar.title("🏢 ASHRAE Energy Explorer")
st.sidebar.caption("LightGBM v1 · RMSLE **0.7343**")
st.sidebar.markdown("---")

# Build display labels for buildings
summary_df["_label"] = summary_df.apply(
    lambda r: (
        f"Building {int(r['building_id'])} — "
        f"{PRIMARY_USE_LABELS.get(int(r['primary_use']), 'Unknown')} "
        f"(Site {int(r['site_id'])})"
    ),
    axis=1,
)

# Default: building with lowest RMSLE
best_idx = int(summary_df["rmsle_building"].idxmin())
best_bid = int(summary_df.loc[best_idx, "building_id"])

# Unique buildings for dropdown
unique_buildings = summary_df.drop_duplicates(subset="building_id").sort_values("building_id")
building_options = dict(zip(unique_buildings["building_id"], unique_buildings["_label"]))

selected_bid = st.sidebar.selectbox(
    "Select Building",
    options=list(building_options.keys()),
    format_func=lambda x: building_options[x],
    index=list(building_options.keys()).index(best_bid)
    if best_bid in building_options else 0,
)

# Meter types available for this building
building_meters = summary_df[summary_df["building_id"] == selected_bid]["meter"].tolist()
meter_options = {m: METER_LABELS.get(m, f"Meter {m}") for m in sorted(building_meters)}

selected_meter = st.sidebar.selectbox(
    "Select Meter Type",
    options=list(meter_options.keys()),
    format_func=lambda x: meter_options[x],
)

# Building metadata card
bldg_row = summary_df[
    (summary_df["building_id"] == selected_bid) &
    (summary_df["meter"] == selected_meter)
]

st.sidebar.markdown("---")
st.sidebar.markdown("### Building Details")

if len(bldg_row) > 0:
    r = bldg_row.iloc[0]
    st.sidebar.markdown(f"""
| | |
|---|---|
| **Primary Use** | {PRIMARY_USE_LABELS.get(int(r['primary_use']), 'Unknown')} |
| **Site ID** | {int(r['site_id'])} |
| **Building Age** | {int(r['building_age'])} years |
| **log(sqft)** | {r['log_square_feet']:.2f} |
| **Per-building RMSLE** | {r['rmsle_building']:.4f} |
| **Avg Consumption** | {r['mean_actual']:,.0f} kWh |
| **Data Points** | {int(r['n_rows']):,} |
""")
else:
    st.sidebar.warning("No summary data for this building/meter combination.")

st.sidebar.markdown("---")
st.sidebar.markdown(
    "[GitHub Repo](https://github.com/Yu-Wang20/ASHRAE_Portfolio) · "
    "[Reports](https://yu-wang20.github.io/ASHRAE_Portfolio/)"
)


# ---------------------------------------------------------------------------
# Main panel — filter data once
# ---------------------------------------------------------------------------
bldg_ts = ts_df[
    (ts_df["building_id"] == selected_bid) &
    (ts_df["meter"] == selected_meter)
].sort_values("timestamp").reset_index(drop=True)

tab1, tab2, tab3 = st.tabs(["📈 Time Series", "🔍 SHAP Explanation", "📊 Model Performance"])


# ═══════════════════════════════════════════════════════════════════════════
# Tab 1: Time Series
# ═══════════════════════════════════════════════════════════════════════════
with tab1:
    st.header("Actual vs Predicted Energy Consumption")

    if len(bldg_ts) == 0:
        st.warning("No time-series data available for this building/meter in the validation period.")
    else:
        # Date range
        min_date = bldg_ts["timestamp"].dt.date.min()
        max_date = bldg_ts["timestamp"].dt.date.max()

        # Default: 2-week window starting from midpoint
        import datetime
        mid = min_date + (max_date - min_date) / 2
        default_start = max(min_date, mid - datetime.timedelta(days=7))
        default_end = min(max_date, default_start + datetime.timedelta(days=14))

        date_range = st.slider(
            "Select date range",
            min_value=min_date,
            max_value=max_date,
            value=(default_start, default_end),
            format="YYYY-MM-DD",
        )

        mask = (
            (bldg_ts["timestamp"].dt.date >= date_range[0]) &
            (bldg_ts["timestamp"].dt.date <= date_range[1])
        )
        window = bldg_ts[mask]

        if len(window) == 0:
            st.info("No data in the selected window.")
        else:
            # Build Plotly figure
            fig = go.Figure()

            # Weekend shading
            weekend_blocks = window[window["is_weekend"] == 1]["timestamp"]
            if len(weekend_blocks) > 0:
                # Find contiguous weekend blocks
                wk_dates = weekend_blocks.dt.date.unique()
                for d in wk_dates:
                    if pd.Timestamp(d).dayofweek == 5:  # Saturday
                        fig.add_vrect(
                            x0=str(d), x1=str(d + datetime.timedelta(days=2)),
                            fillcolor="gray", opacity=0.08,
                            layer="below", line_width=0,
                        )

            fig.add_trace(go.Scatter(
                x=window["timestamp"], y=window["actual_reading"],
                mode="lines", name="Actual",
                line=dict(color="#3498db", width=1.5),
            ))
            fig.add_trace(go.Scatter(
                x=window["timestamp"], y=window["predicted_reading"],
                mode="lines", name="Predicted",
                line=dict(color="#e74c3c", width=1.5, dash="dash"),
            ))

            fig.update_layout(
                title=f"Building {selected_bid} — {meter_options[selected_meter]}",
                xaxis_title="Timestamp",
                yaxis_title="Energy Consumption (kWh)",
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
                height=450,
                margin=dict(l=60, r=30, t=60, b=40),
                hovermode="x unified",
            )

            st.plotly_chart(fig, use_container_width=True)

            # Metrics row
            y_true_log = np.log1p(window["actual_reading"].values)
            y_pred_log = np.log1p(window["predicted_reading"].values)
            period_rmsle = float(np.sqrt(np.mean((y_true_log - y_pred_log) ** 2)))

            c1, c2, c3 = st.columns(3)
            c1.metric("Period RMSLE", f"{period_rmsle:.4f}")
            c2.metric("Mean Actual (kWh)", f"{window['actual_reading'].mean():,.1f}")
            c3.metric("Peak Actual (kWh)", f"{window['actual_reading'].max():,.1f}")


# ═══════════════════════════════════════════════════════════════════════════
# Tab 2: SHAP Explanation
# ═══════════════════════════════════════════════════════════════════════════
with tab2:
    st.header("Feature Importance — SHAP Analysis")

    bldg_shap = shap_df[
        (shap_df["building_id"] == selected_bid) &
        (shap_df["meter"] == selected_meter)
    ]

    if len(bldg_shap) == 0:
        st.info(
            "🔒 SHAP data is available for the **top 20 buildings** by data volume only. "
            "This building was not included in the pre-computed SHAP analysis.\n\n"
            "Select a building with ID 0–19 to explore SHAP explanations."
        )
    else:
        # Compute mean |SHAP| per feature
        shap_cols = [c for c in bldg_shap.columns if c.startswith("shap_")]
        mean_shap = bldg_shap[shap_cols].abs().mean().sort_values(ascending=False)

        # Clean up names for display
        mean_shap.index = [c.replace("shap_", "") for c in mean_shap.index]
        top10 = mean_shap.head(10).reset_index()
        top10.columns = ["Feature", "Mean |SHAP|"]

        # Mean signed SHAP for colour
        mean_signed = bldg_shap[shap_cols].mean()
        mean_signed.index = [c.replace("shap_", "") for c in mean_signed.index]
        top10["Direction"] = top10["Feature"].map(
            lambda f: "Pushes UP ↑" if mean_signed.get(f, 0) >= 0 else "Pushes DOWN ↓"
        )
        top10["Color"] = top10["Feature"].map(
            lambda f: "#e74c3c" if mean_signed.get(f, 0) >= 0 else "#3498db"
        )

        fig = go.Figure(go.Bar(
            x=top10["Mean |SHAP|"].values[::-1],
            y=top10["Feature"].values[::-1],
            orientation="h",
            marker_color=top10["Color"].values[::-1],
            text=[f"{v:.4f}" for v in top10["Mean |SHAP|"].values[::-1]],
            textposition="outside",
        ))
        fig.update_layout(
            title=f"Top 10 SHAP Features — Building {selected_bid}",
            xaxis_title="Mean |SHAP value|",
            height=420,
            margin=dict(l=150, r=60, t=50, b=40),
        )
        st.plotly_chart(fig, use_container_width=True)

        # Plain English explanation
        top_feat = top10.iloc[0]["Feature"]
        top_dir = "up" if mean_signed.get(top_feat, 0) >= 0 else "down"
        st.markdown(
            f"**Interpretation:** For Building {selected_bid}, the model's predictions "
            f"are most influenced by **{top_feat}**, which pushes predictions **{top_dir}** "
            f"on average (mean |SHAP| = {top10.iloc[0]['Mean |SHAP|']:.4f}). "
            f"Red bars indicate features that increase predicted consumption; "
            f"blue bars indicate features that decrease it."
        )


# ═══════════════════════════════════════════════════════════════════════════
# Tab 3: Model Performance
# ═══════════════════════════════════════════════════════════════════════════
with tab3:
    st.header("Model Comparison")

    # Comparison table
    comparison = pd.DataFrame([
        {"Model": "OLS Baseline", "RMSLE": 1.8122, "Notes": "Classical MLR, static features only"},
        {"Model": "Ridge (CV)", "RMSLE": 1.8123, "Notes": "L2 regularisation — stability, not accuracy"},
        {"Model": "Lasso (CV)", "RMSLE": 1.8123, "Notes": "L1 sparsity — zeroes out 1 feature"},
        {"Model": "⭐ LightGBM v1", "RMSLE": 0.7343, "Notes": "59.5% improvement over OLS baseline"},
    ])

    st.dataframe(
        comparison.style.highlight_min(subset=["RMSLE"], color="#d4edda"),
        use_container_width=True,
        hide_index=True,
    )

    # Bar chart
    fig = px.bar(
        comparison, x="RMSLE", y="Model", orientation="h",
        color="RMSLE",
        color_continuous_scale=["#2ecc71", "#e74c3c"],
        text=comparison["RMSLE"].apply(lambda x: f"{x:.4f}"),
    )
    fig.update_layout(
        title="RMSLE Comparison (lower is better)",
        showlegend=False,
        coloraxis_showscale=False,
        height=300,
        margin=dict(l=140, r=40, t=50, b=40),
        yaxis=dict(autorange="reversed"),
    )
    fig.update_traces(textposition="outside")
    st.plotly_chart(fig, use_container_width=True)

    st.markdown(
        "> The **59.5% improvement** over OLS demonstrates that nonlinear interactions "
        "and autoregressive lag features capture patterns classical linear models "
        "cannot represent. Each classical assumption violation diagnosed in the "
        "statistical inference notebook has a direct counterpart in what the tree "
        "model captures — **the theory and the engineering are two views of the "
        "same reality.**"
    )

    st.markdown("---")

    c1, c2 = st.columns(2)
    c1.markdown("📂 [GitHub Repository](https://github.com/Yu-Wang20/ASHRAE_Portfolio)")
    c2.markdown("📄 [Interactive Reports (GitHub Pages)](https://yu-wang20.github.io/ASHRAE_Portfolio/)")
