"""
ASHRAE Great Energy Predictor III — Feature Engineering Module

This module transforms the preprocessed DataFrame into model-ready feature
matrices.  Two output modes are provided:

    1. **Full feature matrix** (``get_feature_matrix``) — includes lag and
       rolling features for tree-based models (LightGBM / XGBoost).
    2. **Stats feature matrix** (``get_stats_feature_matrix``) — excludes
       lag/rolling features to avoid look-ahead bias in OLS / classical
       inference notebooks.

Usage
-----
    from src.feature_engineering import FeatureEngineer

    fe = FeatureEngineer(clean_df)
    fe.add_temporal_features()
    fe.add_lag_features()
    fe.add_rolling_features()
    fe.add_building_features()
    fe.add_interaction_features()

    X, y = fe.get_feature_matrix()          # tree models
    X_s, y_s = fe.get_stats_feature_matrix() # OLS / inference
"""

from __future__ import annotations

import logging
from typing import List, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Columns generated by lag / rolling methods — used to separate the two
# output modes in get_feature_matrix vs get_stats_feature_matrix.
_LAG_ROLLING_PREFIX = ("lag_", "rolling_")

# Columns that are identifiers or raw fields not suitable as features.
_NON_FEATURE_COLS = [
    "timestamp",
    "meter_reading",
    "building_id",
    "site_id",
    "year_built",
    "square_feet",
    "floor_count",
]


class FeatureEngineer:
    """Transform preprocessed ASHRAE data into model-ready feature matrices.

    Parameters
    ----------
    df : pd.DataFrame
        Cleaned DataFrame produced by
        :class:`~src.data_preprocessing.ASHRAEPreprocessor`.  Must contain
        at least ``timestamp``, ``meter_reading``, ``building_id``,
        ``meter``, ``site_id``, ``air_temperature``, and
        ``dew_temperature``.

    Attributes
    ----------
    df : pd.DataFrame
        Working copy mutated in-place by each ``add_*`` method.
    """

    def __init__(self, df: pd.DataFrame) -> None:
        self.df: pd.DataFrame = df.copy()
        logger.info(
            "FeatureEngineer initialized — %s rows × %d cols",
            f"{len(self.df):,}",
            self.df.shape[1],
        )

    # ================================================================== #
    # 1. Temporal features
    # ================================================================== #
    def add_temporal_features(self) -> None:
        """Extract calendar and cyclic temporal features from ``timestamp``.

        New columns
        -----------
        - ``hour``          : int 0–23
        - ``day_of_week``   : int 0–6 (Monday = 0)
        - ``month``         : int 1–12
        - ``week_of_year``  : int 1–53
        - ``is_weekend``    : bool
        - ``hour_sin``, ``hour_cos``   : cyclic encoding of hour
        - ``month_sin``, ``month_cos`` : cyclic encoding of month

        Why cyclic encoding?
            Raw integers create an artificial discontinuity (hour 23 →
            hour 0 looks like a huge jump to a linear model). Mapping
            onto the unit circle via sin/cos preserves the true circular
            distance, which is critical for capturing smooth diurnal and
            seasonal periodicity.
        """
        ts = self.df["timestamp"]

        # Calendar integers
        self.df["hour"] = ts.dt.hour.astype(np.int8)
        self.df["day_of_week"] = ts.dt.dayofweek.astype(np.int8)
        self.df["month"] = ts.dt.month.astype(np.int8)
        self.df["week_of_year"] = ts.dt.isocalendar().week.astype(np.int8).values
        self.df["is_weekend"] = ts.dt.dayofweek >= 5

        # Cyclic encoding
        self.df["hour_sin"] = np.sin(2 * np.pi * self.df["hour"] / 24)
        self.df["hour_cos"] = np.cos(2 * np.pi * self.df["hour"] / 24)
        self.df["month_sin"] = np.sin(2 * np.pi * self.df["month"] / 12)
        self.df["month_cos"] = np.cos(2 * np.pi * self.df["month"] / 12)

        logger.info(
            "Added temporal features: hour, day_of_week, month, "
            "week_of_year, is_weekend, hour_sin/cos, month_sin/cos"
        )

    # ================================================================== #
    # 2. Lag features
    # ================================================================== #
    def add_lag_features(self, lags: List[int] | None = None) -> None:
        """Create lagged ``meter_reading`` features per (building_id, meter).

        Parameters
        ----------
        lags : list of int, optional
            Lag offsets in hours.  Defaults to ``[1, 2, 24, 168]``.

            - ``lag_1``   : 1 h ago — captures short-term momentum.
            - ``lag_2``   : 2 h ago — second-order momentum.
            - ``lag_24``  : same hour yesterday — strong diurnal signal.
            - ``lag_168`` : same hour last week — weekly seasonality.

        Notes
        -----
        The first *max(lags)* rows per group will contain NaN in the
        corresponding lag columns.  These NaN are **expected** and should
        be handled by tree models (LightGBM / XGBoost natively support
        missing values) or dropped before training linear models.

        **Do not use lag features in the statistical inference sample** —
        they introduce temporal dependence that violates OLS assumptions.
        Use :meth:`get_stats_feature_matrix` instead.
        """
        if lags is None:
            lags = [1, 2, 24, 168]

        # Ensure temporal order within each group
        self.df = self.df.sort_values(
            ["building_id", "meter", "timestamp"]
        ).reset_index(drop=True)

        grouped = self.df.groupby(["building_id", "meter"])["meter_reading"]

        for lag in lags:
            col_name = f"lag_{lag}"
            self.df[col_name] = grouped.shift(lag)
            nan_count = self.df[col_name].isna().sum()
            logger.info(
                "  %-15s created (%s NaN — expected for first %d rows/group)",
                col_name,
                f"{nan_count:,}",
                lag,
            )

        logger.info("Added %d lag features: %s", len(lags), lags)

    # ================================================================== #
    # 3. Rolling features
    # ================================================================== #
    def add_rolling_features(self, windows: List[int] | None = None) -> None:
        """Create rolling-window statistics per (building_id, meter) group.

        Parameters
        ----------
        windows : list of int, optional
            Window sizes in hours.  Defaults to ``[24, 168]``.

        New columns (per window *w*)
        -----------------------------
        - ``rolling_mean_{w}h`` : rolling mean of ``meter_reading``.
        - ``rolling_std_{w}h``  : rolling standard deviation.

        ``min_periods=1`` is used so that only the very first row per
        group is NaN-free from the start; no rows are lost.
        """
        if windows is None:
            windows = [24, 168]

        # Ensure temporal order
        self.df = self.df.sort_values(
            ["building_id", "meter", "timestamp"]
        ).reset_index(drop=True)

        grouped = self.df.groupby(["building_id", "meter"])["meter_reading"]

        for w in windows:
            mean_col = f"rolling_mean_{w}h"
            std_col = f"rolling_std_{w}h"

            self.df[mean_col] = grouped.transform(
                lambda s: s.rolling(window=w, min_periods=1).mean()
            )
            self.df[std_col] = grouped.transform(
                lambda s: s.rolling(window=w, min_periods=1).std()
            )

            # First row per group will have std = NaN (single observation);
            # fill with 0 since there is no variance to measure.
            self.df[std_col] = self.df[std_col].fillna(0.0)

            logger.info("  window=%dh  → %s, %s", w, mean_col, std_col)

        logger.info("Added rolling features for windows: %s", windows)

    # ================================================================== #
    # 4. Building features
    # ================================================================== #
    def add_building_features(self) -> None:
        """Derive building-level features from metadata columns.

        New columns
        -----------
        - ``log_square_feet`` : ``log1p(square_feet)``
            Variance-stabilising transform.  Energy consumption scales
            roughly proportionally with floor area, so log-transforming
            both the predictor and the target (done in
            :meth:`get_feature_matrix`) linearises the relationship.

        - ``building_age`` : ``2016 - year_built``
            Age relative to the training year.  Older buildings tend to
            have less efficient HVAC systems.  Rows with missing
            ``year_built`` receive ``building_age = 0`` (unknown).

        Dropped columns
        ----------------
        ``square_feet`` and ``year_built`` are dropped after
        transformation to avoid collinear duplicates.
        """
        # log_square_feet
        self.df["log_square_feet"] = np.log1p(self.df["square_feet"])
        logger.info("Created log_square_feet = log1p(square_feet)")

        # building_age (handle NaN year_built)
        if "year_built" in self.df.columns:
            self.df["building_age"] = (
                2016 - self.df["year_built"]
            ).fillna(0).astype(np.int16)
            logger.info(
                "Created building_age = 2016 - year_built (%s rows had missing year_built → 0)",
                f"{self.df['year_built'].isna().sum():,}",
            )
        else:
            self.df["building_age"] = 0
            logger.warning("year_built column not found; building_age set to 0")

        # Drop raw columns
        cols_to_drop = [c for c in ["square_feet", "year_built"] if c in self.df.columns]
        self.df.drop(columns=cols_to_drop, inplace=True)
        logger.info("Dropped raw columns: %s", cols_to_drop)

    # ================================================================== #
    # 5. Interaction features
    # ================================================================== #
    def add_interaction_features(self) -> None:
        """Create physics-informed interaction features.

        New columns
        -----------
        - ``temp_x_hour`` : ``air_temperature × hour_sin``
            Captures the interaction between time-of-day and outdoor
            temperature.  Heating load peaks during cold mornings
            (negative temperature × negative hour_sin) while cooling
            load peaks during hot afternoons (positive × positive).
            This single feature encodes a relationship that would
            otherwise require the model to learn a complex split
            pattern.

        - ``feels_like_approx`` : simplified heat-index proxy
            ``T_air − 0.55 × (1 − RH_proxy) × (T_air − 14.5)``
            where ``RH_proxy = dew_temperature / (air_temperature + ε)``.
            This is a linearised Steadman approximation that gives the
            model an explicit "perceived temperature" signal without
            requiring full psychrometric calculations.

        Prerequisites
        -------------
        :meth:`add_temporal_features` must have been called first (needs
        ``hour_sin``).
        """
        # temp_x_hour
        if "hour_sin" not in self.df.columns:
            raise RuntimeError(
                "hour_sin column missing — call add_temporal_features() first."
            )

        self.df["temp_x_hour"] = (
            self.df["air_temperature"] * self.df["hour_sin"]
        )
        logger.info("Created temp_x_hour = air_temperature × hour_sin")

        # feels_like_approx (simplified heat-index proxy)
        eps = 1e-6  # prevent division by zero
        t_air = self.df["air_temperature"]
        t_dew = self.df["dew_temperature"]

        rh_proxy = t_dew / (t_air + eps)
        self.df["feels_like_approx"] = t_air - 0.55 * (1 - rh_proxy) * (t_air - 14.5)

        logger.info("Created feels_like_approx (simplified heat-index proxy)")

    # ================================================================== #
    # 6. Feature matrix — full (tree models)
    # ================================================================== #
    def get_feature_matrix(
        self, include_lags: bool = True
    ) -> Tuple[pd.DataFrame, pd.Series]:
        """Return the full feature matrix ``X`` and log-target ``y``.

        Parameters
        ----------
        include_lags : bool
            If *True* (default), lag and rolling columns are included.
            Set to *False* to exclude them (equivalent to
            :meth:`get_stats_feature_matrix`).

        Returns
        -------
        X : pd.DataFrame
            Feature matrix.  All identifier and raw-target columns are
            excluded.
        y : pd.Series
            ``log1p(meter_reading)`` — the regression target.

        Important
        ---------
        **Predictions from models trained on this target must be
        inverse-transformed via ``np.expm1(y_pred)`` to recover the
        original kWh scale.**
        """
        # Target: log1p(meter_reading)
        y = np.log1p(self.df["meter_reading"]).rename("log_meter_reading")

        # Build feature set by excluding non-feature columns
        drop_cols = [c for c in _NON_FEATURE_COLS if c in self.df.columns]
        X = self.df.drop(columns=drop_cols)

        if not include_lags:
            lag_rolling_cols = [
                c for c in X.columns if c.startswith(_LAG_ROLLING_PREFIX)
            ]
            X = X.drop(columns=lag_rolling_cols)

        logger.info(
            "Feature matrix: X %s, y %s  (include_lags=%s)",
            X.shape,
            y.shape,
            include_lags,
        )
        return X, y

    # ================================================================== #
    # 7. Feature matrix — stats / inference (no lag/rolling)
    # ================================================================== #
    def get_stats_feature_matrix(self) -> Tuple[pd.DataFrame, pd.Series]:
        """Return a reduced feature matrix for OLS / classical inference.

        This is a convenience wrapper around :meth:`get_feature_matrix`
        with ``include_lags=False``.  It produces a feature set free of
        temporal-dependence artefacts, suitable for use with the 100 k
        stratified sample in the statistical-inference notebooks.

        Excluding lag and rolling features is essential because:
            1. They introduce serial autocorrelation, violating the OLS
               independence assumption.
            2. They create look-ahead bias when the sample is not drawn
               in strict temporal order.
            3. Classical hypothesis tests (t-test, F-test) lose their
               distributional guarantees under dependence.

        Returns
        -------
        X : pd.DataFrame
            Feature matrix WITHOUT lag or rolling columns.
        y : pd.Series
            ``log1p(meter_reading)``.
        """
        logger.info("Building stats feature matrix (no lag/rolling features)")
        return self.get_feature_matrix(include_lags=False)
